config/routes.rb
Ideas::Application.routes.draw do
  
  root to: 'static_pages#home'

  resources :users  
  
  resources :sessions , only: [:new, :create, :destroy]
  resources :project_categories, :only => [:index, :show, :edit]
  resources :projects do
    resources :notes , :only => [:index, :show, :edit]
    resources :tasks , :only => [:index, :show, :edit]
  end

  namespace :api do
    resources :project_categories, :only => [:index, :show,  :create, :update, :destroy]
    resources :projects do
      resources :notes, :only => [:index,:show, :create, :update, :destroy]
      resources :tasks, :only => [:index,:show, :create, :update, :destroy]
    end
  end

  get '/signin', to: 'sessions#new'
  get 'signout', to: "sessions#destroy"
  post "signup", to: "users#new", as: :signup
  get "signup", to: "users#new", as: :new_signup
  
  get '/home', to: "dashboard#show"

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :title, :project_category_id
  
  validates :title, presence: true
  validates :user_id, presence: true
  validates :project_category_id, presence: true
  
  belongs_to :user
  belongs_to :project_category
  has_many :notes
  has_many :tasks
  default_scope order: 'projects.created_at DESC'

  def as_json(options = {})
  	format = {
  		:include => [:project_category, :notes, :tasks]
  	}

  	super format
  end
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :show, :destroy]
  before_filter :fetch_project, only: [:show, :update, :destroy]

  def index
    projects = current_user.projects
    render :json => { data: projects, message: "", success: true, total: projects.length }
  end

  def show
  end

  def create
    success = false
    @project = current_user.projects.build(params[:project])
    if @project.save
      msg = "Project '#{@project.title}' successfully created!"
      success = true
    else
      msg = err_msg(@project)
    end
    render :json => { data: [@project], message: msg, success: success}
  end

  def update
    success = false
    if @project
      if @project.update_attributes(params[:project])
        msg  = "Project '#{@project.title}' updated succesffuly"
        success = true
        data = [@project]
      else
        msg = err_msg(@project)
      end
    else
      data = nil
    end
    render :json => { data: data, success: success, message: msg }
  end

  def destroy
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :signed_in_user, only: [:index, :edit, :update, :show]
	before_filter :correct_project_owner, only: [:edit, :update, :show]
	
	def index	
	end

	def show
	end

	def create
	end

	def destroy
	end

	private
	def correct_project_owner
		@project = current_user.projects.find_by_id(params[:id])
		redirect_to signin_url if @project.nil?
	end
end

app/helpers/api/projects_helper.rb
module Api::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_list.html.erb
<h2>My Projects
<div class="pull-right"> 
	 {{ projects.length }} Projects 
</div>
</h2>
<br>
<div id="projects_container">
	<div class="project header"> 
		<div class="box action"> 
			<span>#</span>
		</div>
		<div class="box content">
			Project Definition
		</div>
		<div class="notes_count">
			Summary 
		</div>
	</div>
	<div class="project" ng-repeat="project in projects"> 
		<div class="box action"> 
			{{ $index + 1 }}.
		</div>
		<div class="box content">
			<div class="title inner">
				<a href="#/{{project.id}}/edit" ng-click="editProject(project)"> {{ project.title }} </a>
			</div>
			<div class="description inner">
				{{ project.description }}
			</div>
			<div> 
				<span class="label label-inverse">category</span> 
				<i class="label label-important">  {{ project.project_category.name }} </i>
			</div>
		</div>
		<div class="notes_count">
			<span class="summary_box">
				<a href="" ng-click="viewNotes(project)"> {{ project.notes.length }} Notes </a>
			</span>
			<span class="summary_box">
				<a href="" ng-click="viewTasks(project)"> {{ project.tasks.length }} Tasks </a>
			</span>
		</div>
	</div>
</div>

app/views/projects/_project_form.html.erb
<div>
	<form class="form-vertical" ng-submit="submit()">
		<div class="control-group">
			<label class="control-label"> Title </label>
			<div class="controls">
				<input type="text" ng-model="project.title">	
			</div>
		</div>
		<div class="control-group">
			<label class="control-label"> Description </label>
			<div class="controls">
				<textarea cols="40" rows="7" ng-model="project.description"></textarea>
			</div>
		</div>
		<div class="control-group">
			<label class="control-label"> Project Category </label>
			<div class="controls">
				<ax-select ng-model="project.project_category_id" watch="userProjectsCategories" prop="id">
					<select 
						class="project_select"
						ng-options="cat.id as cat.name for cat in userProjectsCategories"
						ng-model="project.project_category_id">
					</select>
				</ax-select>
			</div>
		</div>
		<input type="submit" value="{{ buttonText }} Project" class="btn btn-success" >
		<input type="button" value="Cancel" class="btn" ng-click="clear()">
		<div class="ax-loader" visible="isSaving" text="Saving Project ...."></div>
	</form>
</div>

app/views/projects/edit.html.erb
<div>
	<div class="pull-left">
		<div id="the_project_form">
			<legend>Edit Idea</legend>
			<%= render "project_form" %>
		</div>
	</div>
	<div class="pull-right" id="wrapper">
		<%= render 'list' %>
	</div>
</div>

app/views/projects/index.html.erb
<% provide(:title, "Projects") %>
<br>
<div ng-controller="AppController" id="projects_notes_tasks_container">
	<tabs>
		<pane title="Projects" visible="view.showProjects">
			<div class="clearfix">
				<div ng-controller="ProjectsController">
					<div id="the_project_form" class="pull-left">
						<legend> {{ formTitle }} Project</legend>
						<%= render "project_form" %>
					</div>
					<div class="pull-right" id="wrapper">
				  	<%=  render "list" %>
					</div>
				</div>
			</div>
		</pane>
		<pane title="Notes" visible="view.showNotes">
			<div ng-controller="NotesController" class="clearfix">
				<div class="pull-left" id="note_form">
					<legend> {{ formTitle }} note </legend>
					<%= render "notes/note_form" %>
				</div>
				<div class="pull-right" id="notes_list">
					<%= render "notes/list" %>	
				</div>
				<%= render "notes/note_dialogs" %>
			</div>
		</pane>
		<pane title="Tasks" visible="view.showTasks">
			<div ng-controller="TasksController" class="tasks-container">
				<%= render "tasks/list" %>
			</div>
		</pane>
	</tabs>
</div>

app/views/projects/show.html.erb
<h2>Notes: <%= @project.title %>
	<span class="pull-right note_tasks_back_link">
		<%= link_to "Tasks", project_tasks_path(@project) %>
	</span>
</h2>
<div class="row">
	<tabs>
		<pane title="Notes">
			<div ng-controller="NotesController">
				<div class="span4" >
				<div id="note_form">
					<legend> {{ formTitle }} note</legend>
					<%= render "notes/note_form" %>
				</div>
			</div>
			<div class="span8">
				<%= render "notes/list" %>
			</div>
			</div>
		</pane>
		<pane title="Tasks">
			<div>

			</div>
		</pane>
	</tabs>
</div>