config/routes.rb
Ideas::Application.routes.draw do
  
  root to: 'static_pages#home'

  resources :users  
  
  resources :sessions , only: [:new, :create, :destroy]
  resources :project_categories, :only => [:index, :show, :edit]
  resources :projects do
    resources :notes , :only => [:index, :show, :edit]
    resources :tasks , :only => [:index, :show, :edit]
  end

  namespace :api do
    resources :project_categories, :only => [:index, :show,  :create, :update, :destroy]
    resources :projects do
      resources :notes, :only => [:index,:show, :create, :update, :destroy]
      resources :tasks, :only => [:index,:show, :create, :update, :destroy]
    end
  end

  get '/signin', to: 'sessions#new'
  get 'signout', to: "sessions#destroy"
  post "signup", to: "users#new", as: :signup
  get "signup", to: "users#new", as: :new_signup
  
  get '/home', to: "dashboard#show"

end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
  attr_accessible :description, :name
  validates :name, presence: true
  validates :user_id, presence: true

  has_many :projects
  belongs_to :user
  default_scope order: 'project_categories.created_at DESC'
end

app/controllers/api/project_categories_controller.rb
class Api::ProjectCategoriesController < ApplicationController
   before_filter :signed_in_user, only: [:index, :edit, :update, :show, :destroy]
  def index
    project_categories = current_user.project_categories 
    render :json => { data: project_categories, message: "", success: true ,total: project_categories.length}
  end

  def show
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/project_categories_controller.rb
class ProjectCategoriesController < ApplicationController
	before_filter :signed_in_user, only: [:index, :edit, :update]
	before_filter :correct_project_category_owner, only: [:edit, :update]

	def index
		@project_categories = current_user.project_categories
		@project_category = ProjectCategory.new
	end

	def create
		@project_category =current_user.project_categories.build(params[:project_category])
		if @project_category.save
			flash[:success] = "Project Category created"
		else
			flash[:error] = @project_category.errors.full_messages.to_sentence
		end
		redirect_to project_categories_url
	end

	def edit
		@project_categories = current_user.project_categories
		@project_category = ProjectCategory.find(params[:id])
	end

	def update
		@project_category = ProjectCategory.find(params[:id])
		if @project_category.update_attributes(params[:project_category])
			flash[:success] = "Project Category Saved"
			redirect_to project_categories_url
		else
			flash.now[:error] = "Error : " + @project_category.errors.full_messages.to_sentence 
			@project_categories = ProjectCategory.all
			render 'edit'
		end
	end

	def correct_project_category_owner
		@project_category = current_user.project_categories.find_by_id(params[:id])
		redirect_to signin_url if @project_category.nil?
	end
end

app/helpers/api/project_categories_helper.rb
module Api::ProjectCategoriesHelper
end

app/helpers/project_categories_helper.rb
module ProjectCategoriesHelper
end

app/views/project_categories/_list.html.erb
<h2>Project Categories 
<div class="pull-right">
	<span class="badge badge-success">  
		<%= @project_categories.count %> 
	</span> <i> Categories </i>
</div>
</h2>
<br>
<% if not @project_categories.empty? %>
<div>
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th>Name</th>
				<th>Description</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @project_categories.each do |project_category| %>
			<tr>
				<td class="action_column"> <%= @project_categories.index(project_category) + 1 %>. </td>
				<td> <%= project_category.name %> </td>
				<td> <%= project_category.description %></td>
				<td> 
					<a href="<%= edit_project_category_path(project_category) %>"> 
						<i class="icon icon-pencil"></i> 
					</a> 
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>
<% else %>
	<div class="pull-right">

	</div>
<% end %>

app/views/project_categories/_project_category_form.html.erb
<%= form_for(@project_category) do |f| %>
  <div>
  	<%= f.label :name %>
  	<%= f.text_field :name %>
  </div>

  <div>
  	<%= f.label :description %>
  	<%= f.text_field :description %>
  </div>
  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/project_categories/edit.html.erb
<div>
	<div class="pull-left">
		<div id="the_project_form">
			<legend>Edit Project Category</legend>
			<%= render "project_category_form" %>
		</div>
	</div>
	<div class="pull-right" id="wrapper">
		<%= render 'list' %>
	</div>
</div>

app/views/project_categories/index.html.erb
<div>
	<div class="pull-left">
		<div id="the_project_form">
			<legend>Add Project Category</legend>
			<%= render "project_category_form" %>
		</div>
	</div>
	<div class="pull-right" id="wrapper">
		<%= render 'list' %>
	</div>
</div>