config/routes.rb
Ideas::Application.routes.draw do
  
  root to: 'static_pages#home'

  resources :users  
  
  resources :sessions , only: [:new, :create, :destroy]
  resources :project_categories, :only => [:index, :show, :edit]
  resources :projects do
    resources :notes , :only => [:index, :show, :edit]
    resources :tasks , :only => [:index, :show, :edit]
  end

  namespace :api do
    resources :project_categories, :only => [:index, :show,  :create, :update, :destroy]
    resources :projects do
      resources :notes, :only => [:index,:show, :create, :update, :destroy]
      resources :tasks, :only => [:index,:show, :create, :update, :destroy]
    end
  end

  get '/signin', to: 'sessions#new'
  get 'signout', to: "sessions#destroy"
  post "signup", to: "users#new", as: :signup
  get "signup", to: "users#new", as: :new_signup
  
  get '/home', to: "dashboard#show"

end

app/models/input.rb
class Input < ActiveRecord::Base
	STATUS = {  pending: 1,  started: 2, completed: 3 , note: 10 }.freeze

  attr_accessible :content, :status, :project
 
  validates :content, presence: true
  validates :project_id, presence: true
  validates :status, :presence => true, :inclusion => { in: STATUS }

  def status
  	STATUS.key(read_attribute(:status))
  end

  def status=(value)
    unless value.is_a?(Symbol)
      value = value.to_sym
    end
  	write_attribute(:status, STATUS[value])
  end	

end

app/models/note.rb
class Note < Input
	belongs_to :project
  before_validation(:on => :create) do
  	self.status = :note
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :description, :title, :project_category_id
  
  validates :title, presence: true
  validates :user_id, presence: true
  validates :project_category_id, presence: true
  
  belongs_to :user
  belongs_to :project_category
  has_many :notes
  has_many :tasks
  default_scope order: 'projects.created_at DESC'

  def as_json(options = {})
  	format = {
  		:include => [:project_category, :notes, :tasks]
  	}

  	super format
  end
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
  attr_accessible :description, :name
  validates :name, presence: true
  validates :user_id, presence: true

  has_many :projects
  belongs_to :user
  default_scope order: 'project_categories.created_at DESC'
end

app/models/task.rb
class Task < Input

  belongs_to :project
    
  scope :find_users_tasks_by_status, lambda{ |status, user, project|
  	{
  		:include => :project,
      :order => "inputs.created_at DESC",
  		:conditions => [ "status = :status AND projects.user_id = :user_id AND project_id = :project_id" , 
        { :status => Task::STATUS[status], :user_id => user.id , :project_id => project.id} ]
  	}
  }

  def change_status()
    out = nil
    if self.status == :pending
      self.status = :started
    elsif self.status == :started
      self.status = :completed
    else
    end 
    # self.save
  end

  # STATUS = { pending: 1,  started: 2, completed: 3  }.freeze

  # attr_accessible :status, :content, :note, :project

  # belongs_to :note
  # belongs_to :project

  # validates :content, presence: true
  # validates :note_id, presence: true
  # validates :status, :presence => true, :inclusion => { in: STATUS }
  # validates :project_id, presence: true

  # scope :find_users_tasks_by_status, lambda{ |status, user, project|
  #   {
  #     :include => :project,
  #     :order => "tasks.created_at DESC",
  #     :conditions => [ "tasks.status = :status AND projects.user_id = :user_id AND tasks.project_id = :project_id" , 
  #       { :status => Task::STATUS[status], :user_id => user.id , :project_id => project.id} ]
  #   }
  # }

  # def status
  #   STATUS.key(read_attribute(:status))
  # end

  # def status=(value)
  #    write_attribute(:status, STATUS[value])
  # end

  # def change_status()
  #   out = nil
  #   if self.status == :pending
  #     self.status = :started
  #   elsif self.status == :started
  #     self.status = :completed
  #   else
  #   end 
  #   # self.save
  # end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation

  has_secure_password
  has_many :projects
  has_many :project_categories

  before_save do |user|
  	user.email = email.downcase
  end

  before_save  :create_remember_token 

  after_create :create_default_project_category

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 } , on: :create
  validates :password_confirmation, presence: true, on: :create

  
  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    def create_default_project_category
      self.project_categories.build(name: "None", description: "None")
    end

    def password_required
      self.new_record?
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	def show 
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	def edit
	end

	def update
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :signed_in_user, only: [:index, :edit, :update, :show]
	before_filter :correct_project_owner, only: [:edit, :update, :show]
	
	def index	
	end

	def show
	end

	def create
	end

	def destroy
	end

	private
	def correct_project_owner
		@project = current_user.projects.find_by_id(params[:id])
		redirect_to signin_url if @project.nil?
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end
	
	def create
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in user
			redirect_to projects_path
		else 
			flash.now[:error] = "Invalid email/password combination"
			render "new"
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :signed_in_user, only: [:index] 

  def index
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.create(params[:user])
  	if @user.save
      
      UserEmail.signup_notify(@user).deliver

  		sign_in @user
  		flash[:success] = "Welcome to My Tots. Quickly start keeping track of your Ideas"
  		redirect_to projects_url
  	else
  		flash[:error] = err_msg(@user)
  		redirect_to new_signup_url
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end


  def update
  	@user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "User updated successfully"
      redirect_to @user
    else
      flash.now[:error] = err_msg(user)
      render 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "My Tots"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end

	def pluralize_without_count(count, noun, text = nil)
	  	count == 1 ? " #{noun}#{text}" : "#{noun.pluralize}#{text}"
	end

  def active_klass(in_page, out_page)
   in_page.downcase == out_page.downcase ? "active" : ""
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= User.find_by_remember_token(cookies[:remember_token])
	end

	def signed_in?
		!current_user.nil?
	end

	def signed_in_user
		unless signed_in?
			store_location
			redirect_to signin_url , notice: "Please Sign In"
		end
	end

	def store_location
		session[:return_to] = request.url
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
	Time::DATE_FORMATS[:due_date] = "due on %B %d at %I:%M %p"
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    My Tots
  </small>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "My TOTS", root_path, id: "logo", class: "brand" %>
      <div class="nav-collapse">
        <ul class="nav pull-right">
          <% if signed_in? %>
               <li class="<%= active_klass('Home', yield( :title )) %>">
                   <%= link_to "Home" , root_path %>
                </li>
                <li class="<%= active_klass('Projects', yield( :title )) %>">
                   <%= link_to "Projects", projects_path  %>
                </li>
                <li class="<%= active_klass('Profile', yield( :title )) %>">
                   <%= link_to "Profile", user_path(current_user) %>
                </li>
                <li>
                   <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
           <% else %>
                <li> <%= link_to "Sign in", signin_path %> </li>
           <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app">
<head>
  <title> <%= full_title(yield(:title)) %> </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <ax-msg></ax-msg>
    	<% flash.each do |key,value| %>
    		<div class="alert alert-<%= key %>"><%= value %></div>
    	<% end %>
    </div>
    <div class="container">
       <%= yield %>
    </div>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/user_email/signup_notify.html.erb
<p>
	Hello  <%= @user.name %>, Welcome to My Tots
</p>
	
<p>
	Thanks for signing up! We are Excited to have you here.
</p>

<p>	
	Your login is <%= @user.email %>. Quickly start creating your creative project ideas. Remember every idea or project no matter how small is important
</p>

app/views/user_email/signup_notify.text.erb
Hello  <%= @user.name %>, Welcome to My Tots
===============================================

Thanks for signing up! We are Excited to have you here.

Your login is <%= @user.email %>. Quickly start creating your creative project ideas. Remember every idea or project no matter how small is important